//
//  SettlementOptimizationPDFExporter.swift
//  Tabi Split
//
//  Created by Elian Richard on 11/08/26.
//

import UIKit

/// One participant's balance breakdown, mirroring `OptimizationPersonCard`.
struct OptimizationPersonPDFData {
    var name: String
    var isCurrentUser: Bool
    var lent: Float
    var debt: Float
    var balance: Float
    /// Human-readable status ("Should pay" / "Should receive" / "Settled").
    var statusText: String
}

/// One "who pays whom" line, mirroring a row of `OptimizationRecapCard`.
struct OptimizationRecapPDFData {
    var fromName: String
    var toName: String
    var amount: Float
}

/// One person sharing a line item, and how much of it they cover.
struct OptimizationAssigneePDFData {
    var name: String
    var share: Float
}

/// A single line item within an expense (e.g. "Chicken", "Rice"), and who shares it.
struct OptimizationExpenseItemPDFData {
    var name: String
    var quantity: Float
    var price: Float
    var assignees: [OptimizationAssigneePDFData]
}

/// An additional charge on an expense (e.g. Tax, Service, Discount).
struct OptimizationAdditionalChargePDFData {
    var typeName: String
    var amount: Float
}

/// One expense of the event: the receipt name, who paid for it, the total, the
/// split method, and — for custom splits — its finer line-item breakdown plus
/// any additional charges (tax / service / discount / other).
struct OptimizationExpensePDFData {
    var name: String
    var payerName: String
    var amount: Float
    /// Whether the expense was split equally. Equal splits omit the item breakdown.
    var isEquallySplit: Bool
    /// For equal splits, the per-person amount (total ÷ participants); nil otherwise.
    var equalSplitPerPerson: Float?
    var items: [OptimizationExpenseItemPDFData]
    var additionalCharges: [OptimizationAdditionalChargePDFData]
}

/// Immutable snapshot of everything needed to render the Settlement Optimization
/// page as a PDF. Extracted from `EventViewModel` so the exporter stays a pure,
/// testable function.
struct SettlementOptimizationPDFData {
    var eventName: String
    var generatedByName: String
    var persons: [OptimizationPersonPDFData]
    var recap: [OptimizationRecapPDFData]
    var expenses: [OptimizationExpensePDFData]
}

/// Builds a paginated, shareable PDF of the Settlement Optimization page.
enum SettlementOptimizationPDFExporter {

    // MARK: - Money formatting

    /// Formats an amount the same way the app UI does: an `Rp` prefix plus an
    /// explicit `+`/`-` sign so positives and negatives read correctly even in
    /// grayscale (where the color coding is lost).
    private static func formatMoney(_ amount: Float, showSign: Bool = false) -> String {
        let magnitude = abs(amount).formatPrice(isShowSign: false)
        guard showSign else { return "Rp\(magnitude)" }
        let sign = amount < 0 ? "-" : "+"
        return "\(sign)Rp\(magnitude)"
    }

    // MARK: - Public API

    static func generatePDF(from data: SettlementOptimizationPDFData) -> Data {
        let pageSize = CGRect(x: 0, y: 0, width: 595, height: 842) // A4 portrait
        let leftMargin: CGFloat = 40
        let rightMargin: CGFloat = 40
        let contentWidth = pageSize.width - leftMargin - rightMargin
        let pageBottom: CGFloat = pageSize.height - 55

        var pageY: CGFloat = 40

        let renderer = UIGraphicsPDFRenderer(bounds: pageSize)

        return renderer.pdfData { context in
            context.beginPage()

            // ---- Header ----
            pageY = drawCenteredTitle("\(data.eventName) — Optimization Details", maxY: pageY, pageWidth: pageSize.width)
            let now = Date()
            pageY = drawCenteredSubtitle(
                "Generated by \(data.generatedByName)  •  \(now.customDateFormat("dd MMM yyyy HH:mm").string(from: now))",
                maxY: pageY, pageWidth: pageSize.width
            )
            pageY += 20

            // ---- Participant balances ----
            pageY = drawSectionTitle("Participant Balances", maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth)
            pageY += 4

            if data.persons.isEmpty {
                pageY = drawInfoRow(label: "No participants.", value: "", maxY: pageY,
                                    leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
            }

            for person in data.persons {
                if pageY + 84 > pageBottom {
                    context.beginPage()
                    pageY = drawSectionTitle("Participant Balances (cont.)", maxY: 40.0,
                                             leftMargin: leftMargin, contentWidth: contentWidth)
                    pageY += 4
                }
                pageY = drawPersonCard(person, maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
                pageY += 12
            }

            pageY += 12

            // ---- Recapitulation (who pays whom) ----
            if pageY + 60 > pageBottom {
                context.beginPage()
                pageY = 40
            }
            pageY = drawSectionTitle("Recapitulation", maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth)
            pageY += 6
            pageY = drawRecapHeader(maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
            pageY += 4

            if data.recap.isEmpty {
                pageY = drawInfoRow(label: "Everyone is settled — no payments needed.", value: "", maxY: pageY,
                                    leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
            }

            for entry in data.recap {
                if pageY > pageBottom {
                    context.beginPage()
                    pageY = drawSectionTitle("Recapitulation (cont.)", maxY: 40.0,
                                             leftMargin: leftMargin, contentWidth: contentWidth)
                    pageY += 6
                    pageY = drawRecapHeader(maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
                    pageY += 4
                }
                pageY = drawRecapRow(entry, maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
            }

            // ---- Expense list with per-item breakdown (always starts on its own page) ----
            context.beginPage()
            pageY = 40
            pageY = drawSectionTitle("Expense List", maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth)
            pageY += 6

            if data.expenses.isEmpty {
                pageY = drawInfoRow(label: "No expenses recorded.", value: "", maxY: pageY,
                                    leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)
            }

            for expense in data.expenses {
                // Keep the expense header with at least its first item on the same page.
                if pageY + 54 > pageBottom {
                    context.beginPage()
                    pageY = drawSectionTitle("Expense List (cont.)", maxY: 40.0,
                                             leftMargin: leftMargin, contentWidth: contentWidth)
                    pageY += 6
                }
                pageY = drawExpenseGroupHeader(expense, maxY: pageY, leftMargin: leftMargin, contentWidth: contentWidth, pageWidth: pageSize.width)

                // Equal splits carry no per-item detail — the header already says how it was split.
                if !expense.isEquallySplit {
                    if expense.items.isEmpty {
                        pageY = drawExpenseItemRow(name: "No itemised breakdown.", quantity: nil, price: nil,
                                                   maxY: pageY, leftMargin: leftMargin, pageWidth: pageSize.width)
                    }

                    for item in expense.items {
                        if pageY > pageBottom {
                            context.beginPage()
                            pageY = drawSectionTitle("Expense List (cont.)", maxY: 40.0,
                                                     leftMargin: leftMargin, contentWidth: contentWidth)
                            pageY += 6
                        }
                        pageY = drawExpenseItemRow(name: item.name, quantity: item.quantity, price: item.price,
                                                   maxY: pageY, leftMargin: leftMargin, pageWidth: pageSize.width)

                        // Assignees (who shares this item) sit indented under it.
                        if !item.assignees.isEmpty {
                            if pageY > pageBottom {
                                context.beginPage()
                                pageY = drawSectionTitle("Expense List (cont.)", maxY: 40.0,
                                                         leftMargin: leftMargin, contentWidth: contentWidth)
                                pageY += 6
                            }
                            pageY = drawAssigneesRow(item.assignees, maxY: pageY, leftMargin: leftMargin, pageWidth: pageSize.width)
                        }
                    }

                    // Additional charges (tax / service / discount / other) — no assignees.
                    for charge in expense.additionalCharges {
                        if pageY > pageBottom {
                            context.beginPage()
                            pageY = drawSectionTitle("Expense List (cont.)", maxY: 40.0,
                                                     leftMargin: leftMargin, contentWidth: contentWidth)
                            pageY += 6
                        }
                        pageY = drawExpenseItemRow(name: charge.typeName, quantity: nil, price: charge.amount,
                                                   maxY: pageY, leftMargin: leftMargin, pageWidth: pageSize.width)
                    }
                }
                pageY += 14
            }
        }
    }

    // MARK: - Drawing helpers

    private static func drawCenteredTitle(_ text: String, maxY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 20, weight: .bold),
            .foregroundColor: UIColor.black,
        ]
        let size = (text as NSString).size(withAttributes: attributes)
        let rect = CGRect(x: (pageWidth - size.width) / 2, y: maxY, width: size.width, height: size.height)
        (text as NSString).draw(in: rect, withAttributes: attributes)
        return maxY + size.height + 8
    }

    private static func drawCenteredSubtitle(_ text: String, maxY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .regular),
            .foregroundColor: UIColor.gray,
        ]
        let size = (text as NSString).size(withAttributes: attributes)
        let rect = CGRect(x: (pageWidth - size.width) / 2, y: maxY, width: size.width, height: size.height)
        (text as NSString).draw(in: rect, withAttributes: attributes)
        return maxY + size.height
    }

    private static func drawSectionTitle(_ text: String, maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat) -> CGFloat {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 16, weight: .semibold),
            .foregroundColor: UIColor.black,
        ]
        let size = (text as NSString).size(withAttributes: attributes)
        let rect = CGRect(x: leftMargin, y: maxY, width: contentWidth, height: size.height + 8)
        (text as NSString).draw(in: rect, withAttributes: attributes)
        UIColor.separator.setFill()
        UIRectFill(CGRect(x: leftMargin, y: maxY + size.height + 2, width: contentWidth, height: 1))
        return maxY + size.height + 14
    }

    /// Mirrors `OptimizationPersonCard`: name, lent/debt, and the balance status.
    private static func drawPersonCard(_ person: OptimizationPersonPDFData, maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let cardHeight: CGFloat = 80
        let box = CGRect(x: leftMargin, y: maxY, width: contentWidth, height: cardHeight)
        UIColor.systemGroupedBackground.setFill()
        UIRectFill(box)
        UIColor.separator.setStroke()
        UIBezierPath(rect: box).stroke()

        let nameAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 15, weight: .semibold),
            .foregroundColor: UIColor.black,
        ]
        let labelAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .regular),
            .foregroundColor: UIColor.gray,
        ]
        let lentAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13, weight: .medium),
            .foregroundColor: UIColor.systemGreen,
        ]
        let debtAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13, weight: .medium),
            .foregroundColor: UIColor.systemRed,
        ]
        let statusAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13, weight: .bold),
            .foregroundColor: person.balance < 0 ? UIColor.systemRed : UIColor.systemGreen,
        ]

        let name = person.isCurrentUser ? "\(person.name) (You)" : person.name
        (name as NSString).draw(at: CGPoint(x: box.minX + 16, y: box.minY + 10), withAttributes: nameAttributes)

        // Lent / debt columns.
        let colWidth = (box.width - 32) / 2
        ("Total Lent" as NSString).draw(at: CGPoint(x: box.minX + 16, y: box.minY + 34), withAttributes: labelAttributes)
        (formatMoney(person.lent) as NSString).draw(at: CGPoint(x: box.minX + 16, y: box.minY + 48), withAttributes: lentAttributes)
        ("Total Debt" as NSString).draw(at: CGPoint(x: box.minX + 16 + colWidth, y: box.minY + 34), withAttributes: labelAttributes)
        (formatMoney(person.debt) as NSString).draw(at: CGPoint(x: box.minX + 16 + colWidth, y: box.minY + 48), withAttributes: debtAttributes)

        // Status + net balance, right-aligned.
        let statusLine = "\(person.statusText) \(formatMoney(person.balance, showSign: true))" as NSString
        let statusSize = statusLine.size(withAttributes: statusAttributes)
        statusLine.draw(at: CGPoint(x: box.maxX - 16 - statusSize.width, y: box.minY + 10), withAttributes: statusAttributes)

        return box.maxY
    }

    private static func drawRecapHeader(maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .semibold),
            .foregroundColor: UIColor.gray,
        ]
        ("Payment" as NSString).draw(at: CGPoint(x: leftMargin, y: maxY), withAttributes: attributes)
        ("Amount" as NSString).draw(at: CGPoint(x: pageWidth - leftMargin - 80, y: maxY), withAttributes: attributes)
        UIColor.separator.setFill()
        UIRectFill(CGRect(x: leftMargin, y: maxY + 18, width: contentWidth, height: 1))
        return maxY + 24
    }

    private static func drawRecapRow(_ entry: OptimizationRecapPDFData, maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let paymentAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13, weight: .medium),
            .foregroundColor: UIColor.black,
        ]
        let amountAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13, weight: .semibold),
            .foregroundColor: UIColor.black,
        ]

        let maxNameWidth = (pageWidth - leftMargin - 90) - leftMargin
        let payment = ("\(entry.fromName)  →  \(entry.toName)" as NSString)
            .truncated(toWidth: maxNameWidth, using: paymentAttributes)
        payment.draw(at: CGPoint(x: leftMargin, y: maxY), withAttributes: paymentAttributes)

        let amount = formatMoney(entry.amount) as NSString
        let amountSize = amount.size(withAttributes: amountAttributes)
        amount.draw(at: CGPoint(x: pageWidth - leftMargin - max(amountSize.width, 80), y: maxY), withAttributes: amountAttributes)

        return maxY + max(payment.size(withAttributes: paymentAttributes).height, 18) + 6
    }

    /// The expense-level header: receipt name, who paid, and the total — the item
    /// rows drawn by `drawExpenseItemRow` sit indented beneath it.
    private static func drawExpenseGroupHeader(_ expense: OptimizationExpensePDFData, maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let nameAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .bold),
            .foregroundColor: UIColor.black,
        ]
        let payerAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .regular),
            .foregroundColor: UIColor.gray,
        ]
        let amountAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .bold),
            .foregroundColor: UIColor.black,
        ]

        let drawName = (expense.name as NSString).truncated(toWidth: 300, using: nameAttributes)
        drawName.draw(at: CGPoint(x: leftMargin, y: maxY), withAttributes: nameAttributes)

        let amount = formatMoney(expense.amount) as NSString
        let amountSize = amount.size(withAttributes: amountAttributes)
        amount.draw(at: CGPoint(x: pageWidth - leftMargin - max(amountSize.width, 80), y: maxY), withAttributes: amountAttributes)

        let payerY = maxY + drawName.size(withAttributes: nameAttributes).height + 1
        var splitLabel = expense.isEquallySplit ? "Split equally" : "Split custom"
        if expense.isEquallySplit, let perPerson = expense.equalSplitPerPerson {
            splitLabel += " (\(formatMoney(perPerson))/person)"
        }
        ("Paid by \(expense.payerName)  •  \(splitLabel)" as NSString)
            .draw(at: CGPoint(x: leftMargin, y: payerY), withAttributes: payerAttributes)

        let bottom = payerY + ("Paid by" as NSString).size(withAttributes: payerAttributes).height + 6
        UIColor.separator.setFill()
        UIRectFill(CGRect(x: leftMargin, y: bottom, width: contentWidth, height: 1))
        return bottom + 6
    }

    /// One indented line item beneath an expense header. Pass nil quantity/price
    /// for placeholder text (e.g. "No itemised breakdown.").
    private static func drawExpenseItemRow(name: String, quantity: Float?, price: Float?, maxY: CGFloat, leftMargin: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let indent = leftMargin + 16
        let nameAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .regular),
            .foregroundColor: UIColor.darkGray,
        ]
        let priceAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .medium),
            .foregroundColor: UIColor.black,
        ]

        var label = name
        if let quantity, quantity > 0 {
            // Show whole quantities without a trailing ".0".
            let qtyText = quantity.truncatingRemainder(dividingBy: 1) == 0 ? String(Int(quantity)) : String(quantity)
            label = "\(name)  ×\(qtyText)"
        }
        let drawName = (label as NSString).truncated(toWidth: 360, using: nameAttributes)
        drawName.draw(at: CGPoint(x: indent, y: maxY), withAttributes: nameAttributes)

        if let price {
            let priceText = formatMoney(price) as NSString
            let priceSize = priceText.size(withAttributes: priceAttributes)
            priceText.draw(at: CGPoint(x: pageWidth - leftMargin - max(priceSize.width, 70), y: maxY), withAttributes: priceAttributes)
        }

        return maxY + max(drawName.size(withAttributes: nameAttributes).height, 16) + 5
    }

    /// The list of people sharing an item, indented under the item row.
    private static func drawAssigneesRow(_ assignees: [OptimizationAssigneePDFData], maxY: CGFloat, leftMargin: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let indent = leftMargin + 32
        let attributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .regular),
            .foregroundColor: UIColor.gray,
        ]
        let parts = assignees.map { assignee -> String in
            guard assignee.share > 0 else { return assignee.name }
            // Share is a multiplier/portion, not a price — show whole values without ".0".
            let shareText = assignee.share.truncatingRemainder(dividingBy: 1) == 0
                ? String(Int(assignee.share))
                : String(assignee.share)
            return "\(assignee.name) (\(shareText)x)"
        }
        let text = ("Shared by: " + parts.joined(separator: ", ") as NSString)
            .truncated(toWidth: pageWidth - leftMargin - indent, using: attributes)
        text.draw(at: CGPoint(x: indent, y: maxY), withAttributes: attributes)
        return maxY + text.size(withAttributes: attributes).height + 5
    }

    private static func drawInfoRow(label: String, value: String, maxY: CGFloat, leftMargin: CGFloat, contentWidth: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let labelAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .regular),
            .foregroundColor: UIColor.darkGray,
        ]
        let valueAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .medium),
            .foregroundColor: UIColor.black,
        ]
        let labelSize = (label as NSString).size(withAttributes: labelAttributes)
        (label as NSString).draw(at: CGPoint(x: leftMargin, y: maxY), withAttributes: labelAttributes)
        let valueSize = (value as NSString).size(withAttributes: valueAttributes)
        (value as NSString).draw(at: CGPoint(x: pageWidth - leftMargin - valueSize.width, y: maxY), withAttributes: valueAttributes)
        return maxY + max(labelSize.height, valueSize.height) + 6
    }
}

private extension NSString {
    /// Returns a copy of the receiver truncated (with an ellipsis) if it is wider than `maxWidth`.
    func truncated(toWidth maxWidth: CGFloat, using attributes: [NSAttributedString.Key: Any]) -> NSString {
        if size(withAttributes: attributes).width <= maxWidth { return self }
        var length = self.length
        while length > 0 {
            length -= 1
            let candidate = substring(to: length) + "…"
            if (candidate as NSString).size(withAttributes: attributes).width <= maxWidth {
                return candidate as NSString
            }
        }
        return "…" as NSString
    }
}
