name: Tabi Split
settings:
  MARKETING_VERSION: "1.1.3"
  CURRENT_PROJECT_VERSION: 1
  base:
    GENERATE_INFOPLIST_FILE: YES
options:
  bundleIdPrefix: com.sora
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-spm.git
    minorVersion: 4.5.0
  JWTDecode:
    url: https://github.com/auth0/JWTDecode.swift.git
    minorVersion: 3.2.0
targets:
  Tabi Split:
    type: application
    platform: iOS
    sources: ["Tabi Split"]
    resources: [Resources]
    files:
      - path: "Tabi Split.app"
        type: wrapper.application
        buildPhase: none
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sora.Tabi
      INFOPLIST_FILE: Tabi Split/Info.plist
      base:
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.1.3"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_ASSET_PATHS: '"Tabi Split/Resources/Preview Content"'
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations:
          ["UIInterfaceOrientationPortrait"]
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        INFOPLIST_KEY_CFBundleDisplayName: "Tabi"
        ENABLE_TESTABILITY: YES
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        Release:
          ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    dependencies:
      - package: Lottie
      - package: JWTDecode
  Tabi Split Tests:
    type: bundle.unit-test
    platform: iOS
    sources: ["Tabi Split Tests"]
    dependencies:
      - target: "Tabi Split"
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Tabi Split.app/Tabi Split"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  Tabi Split:
    build:
      targets:
        Tabi Split: all
        Tabi Split Tests: all
    test:
      targets:
        - name: "Tabi Split Tests"
      gatherCoverageData: true
